export function buildExternalReportHTML(): string {
  const deal = {
    address: '1234 Oak Street, Arlington, TX 76010',
    purchasePrice: 320000,
    estimatedRent: 2200,
    dealScore: 72,
    verdict: 'GO',
    capRate: 5.28,
    cashOnCash: 6.15,
    equityYear5: 98450,
  };

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Investment Summary - ${deal.address}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; padding: 40px; line-height: 1.6; }
    h1 { color: #d4a843; border-bottom: 2px solid #d4a843; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    .metric-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin: 20px 0; }
    .metric-card { background: #f8f9fa; border-radius: 8px; padding: 16px; text-align: center; }
    .metric-value { font-size: 24px; font-weight: bold; color: #d4a843; }
    .metric-label { font-size: 12px; color: #666; text-transform: uppercase; }
    .score-badge { display: inline-block; background: ${deal.dealScore >= 70 ? '#22c55e' : deal.dealScore >= 50 ? '#eab308' : '#ef4444'}; color: white; padding: 8px 16px; border-radius: 20px; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; }
    th { background: #16213e; color: white; }
    .disclaimer { margin-top: 40px; padding: 16px; background: #fff3cd; border-radius: 8px; font-size: 11px; color: #664d03; }
    .footer { margin-top: 20px; font-size: 10px; color: #999; }
  </style>
</head>
<body>
  <h1>Investment Summary</h1>
  <p><strong>Property:</strong> ${deal.address}</p>
  <p><strong>Verdict:</strong> <span class="score-badge">${deal.verdict} (${deal.dealScore})</span></p>

  <h2>Financial Overview</h2>
  <div class="metric-grid">
    <div class="metric-card"><div class="metric-value">$${deal.purchasePrice.toLocaleString()}</div><div class="metric-label">Purchase Price</div></div>
    <div class="metric-card"><div class="metric-value">$${deal.estimatedRent.toLocaleString()}/mo</div><div class="metric-label">Est. Rent</div></div>
    <div class="metric-card"><div class="metric-value">${deal.capRate}%</div><div class="metric-label">Cap Rate</div></div>
    <div class="metric-card"><div class="metric-value">${deal.cashOnCash}%</div><div class="metric-label">Cash-on-Cash</div></div>
  </div>

  <h2>5-Year Equity Projection</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Projected Equity (Year 5)</td><td>$${deal.equityYear5.toLocaleString()}</td></tr>
  </table>

  <h2>Market Summary</h2>
  <p>Arlington, TX is located in the DFW metropolitan area with strong rental demand driven by proximity to AT&T Stadium, University of Texas at Arlington, and major employers along the I-30 corridor. The area has seen consistent population growth and stable property appreciation.</p>

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This investment summary is provided for informational purposes only and does not constitute financial advice. All figures are estimates based on available data at the time of analysis. Actual results may vary. Consult a qualified financial advisor before making investment decisions.
  </div>

  <div class="footer">
    <p>Generated by DealStack on ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>`;
}
