export function buildInternalReportHTML(): string {
  // Hardcoded test data representing a DFW property analysis
  const deal = {
    address: '1234 Oak Street, Arlington, TX 76010',
    purchasePrice: 320000,
    estimatedRent: 2200,
    dealScore: 72,
    verdict: 'GO',
    capRate: 5.28,
    cashOnCash: 6.15,
    dscr: 1.12,
    grm: 12.12,
    noi: 16896,
    monthlyPI: 1704.68,
    equityYear5: 98450,
    equityYear10: 156200,
  };

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Internal Investment Memo - ${deal.address}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; padding: 40px; line-height: 1.6; }
    h1 { color: #d4a843; border-bottom: 2px solid #d4a843; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    .metric-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 20px 0; }
    .metric-card { background: #f8f9fa; border-radius: 8px; padding: 16px; text-align: center; }
    .metric-value { font-size: 24px; font-weight: bold; color: #d4a843; }
    .metric-label { font-size: 12px; color: #666; text-transform: uppercase; }
    .score-badge { display: inline-block; background: ${deal.dealScore >= 70 ? '#22c55e' : deal.dealScore >= 50 ? '#eab308' : '#ef4444'}; color: white; padding: 8px 16px; border-radius: 20px; font-weight: bold; font-size: 18px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; }
    th { background: #16213e; color: white; }
    .section { margin-bottom: 30px; }
    .assumptions { background: #f0f4ff; padding: 16px; border-radius: 8px; }
    .footer { margin-top: 40px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
  </style>
</head>
<body>
  <h1>Internal Investment Memo</h1>
  <p><strong>Property:</strong> ${deal.address}</p>
  <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
  <p><strong>Verdict:</strong> <span class="score-badge">${deal.verdict} (${deal.dealScore})</span></p>

  <div class="section">
    <h2>Key Metrics</h2>
    <div class="metric-grid">
      <div class="metric-card"><div class="metric-value">${deal.capRate}%</div><div class="metric-label">Cap Rate</div></div>
      <div class="metric-card"><div class="metric-value">${deal.cashOnCash}%</div><div class="metric-label">Cash-on-Cash</div></div>
      <div class="metric-card"><div class="metric-value">${deal.dscr}</div><div class="metric-label">DSCR</div></div>
      <div class="metric-card"><div class="metric-value">${deal.grm}</div><div class="metric-label">GRM</div></div>
      <div class="metric-card"><div class="metric-value">$${deal.noi.toLocaleString()}</div><div class="metric-label">NOI</div></div>
      <div class="metric-card"><div class="metric-value">$${deal.monthlyPI.toLocaleString()}</div><div class="metric-label">Monthly P&I</div></div>
    </div>
  </div>

  <div class="section">
    <h2>Deal Score Breakdown</h2>
    <table>
      <tr><th>Component</th><th>Weight</th><th>Score</th></tr>
      <tr><td>Cash-on-Cash Return</td><td>25%</td><td>68</td></tr>
      <tr><td>Cap Rate</td><td>20%</td><td>62</td></tr>
      <tr><td>5-Year Equity Growth</td><td>20%</td><td>78</td></tr>
      <tr><td>Market Score</td><td>15%</td><td>75</td></tr>
      <tr><td>Value-Add Upside</td><td>10%</td><td>80</td></tr>
      <tr><td>Comp Validation</td><td>10%</td><td>72</td></tr>
    </table>
  </div>

  <div class="section">
    <h2>Equity Projections</h2>
    <table>
      <tr><th>Year</th><th>Equity</th></tr>
      <tr><td>Year 5</td><td>$${deal.equityYear5.toLocaleString()}</td></tr>
      <tr><td>Year 10</td><td>$${deal.equityYear10.toLocaleString()}</td></tr>
    </table>
  </div>

  <div class="section assumptions">
    <h2>Assumptions</h2>
    <table>
      <tr><td>Purchase Price</td><td>$${deal.purchasePrice.toLocaleString()}</td></tr>
      <tr><td>Monthly Rent Estimate</td><td>$${deal.estimatedRent.toLocaleString()}</td></tr>
      <tr><td>Down Payment</td><td>20%</td></tr>
      <tr><td>Interest Rate</td><td>7.0%</td></tr>
      <tr><td>Vacancy</td><td>8%</td></tr>
      <tr><td>Management</td><td>9%</td></tr>
      <tr><td>Maintenance</td><td>10%</td></tr>
      <tr><td>CapEx</td><td>5%</td></tr>
      <tr><td>Property Tax Rate</td><td>1.8%</td></tr>
    </table>
  </div>

  <div class="footer">
    <p>CONFIDENTIAL - Internal Use Only. Generated by DealStack on ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}
